backend: 
  name: git-gateway
  branch: master
  repo: ticklemetintine/eleventy-netlify

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{ year }}-{{ month }}-{{ day }}-{{ slug }}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Show in home?", name: "isFeatured", widget: "boolean" }
 
  - name: "testimonials"
    label: "Testimonials"
    folder: "src/testimonials"
    create: true
    slug: "testimonial"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/testimonial.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Testimonial Body", name: "body", widget: "markdown" }
      - { label: "Author", name: "author", widget: "string" }
 
  - label: "Static"
    name: "static"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/static/home.md"
        fields:
          - { label: "Permalink", name: "permalink", widget: "string", default: "/" }
          - { label: "Layout", name: "layout", widget: "string", default: "layouts/index.njk" }
          - { label: "Banner Image", name: "banner", widget: "image" }
          - { label: "Intro", name: "intro", widget: markdown }
          - { label: "Show featured posts?", name: "fp_show", widget: "boolean" }
          - { label: "Featured Post Heading", name: "fp_heading", widget: "string" }
          - { label: "Number of posts", name: "fp_count", widget: "number" }
          - { label: "Outro", name: "outro", widget: "markdown" }
          - { label: "Show testimonials?", name: "ft_show", widget: "boolean" }
          - { label: "Testimonials Section Heading", name: "ft_heading", widget: "string" }
          - { label: "Number of testimonials", name: "ft_count", widget: "number" }

      - label: "About Page"
        name: "about"
        file: "src/static/about.md"
        fields:
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown"}
          - { label: "Layout", name: "layout", widget: "string", default: "layouts/post.njk" }

      - label: "Post Page"
        name: "posts"
        file: "src/static/posts.md"
        fields:
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown"}
          - { label: "Layout", name: "layout", widget: "string", default: "layouts/post.njk" }

      - label: "Widgets"
        name: "widget"
        file: "src/static/widgets.md"
        fields:
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string", default: "layouts/widgets.njk" }
          - { label: "Body", name: "body", widget: "string", output_code_only: false }
          - { label: "Code Heading", name: "code_heading", widget: "string" }
          - { label: "Code", name: "code", widget: "code" }
          - { label: "Color Picker Heading", name: "color_heading", widget: "string" }
          - { label: "Color", name: "color", widget: "color" }
          - { label: "Date Picker Heading", name: "date_heading", widget: "string" }
          - { label: "Date", name: "date", widget: "date" }
          - { label: "Date time Picker Heading", name: "datetime_heading", widget: "string" }
          - { label: "Date time", name: "datetime", widget: "datetime" }
          - { label: "File", name: "file", widget: "file" }
          - { label: "Image", name: "image", widget: "image" }
          - label: "List"
            name: "list"
            widget: "list"
            fields:
              - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
              - {label: Author, name: author, widget: string }
          - { label: "Map", name: "map", widget: "map" }
          - label: "Profile"
            name: "profile"
            widget: "object"
            summary: '{{fields.name}}: {{fields.birthdate}}'
            fields:
              - {label: "Public", name: "public", widget: "boolean", default: true}
              - {label: "Name", name: "name", widget: "string"}
              - label: "Birthdate"
                name: "birthdate"
                widget: "date"
                default: ""
                format: "MM/DD/YYYY"
              - label: "Address"
                name: "address"
                widget: "object"
                collapsed: true
                fields: 
                  - {label: "Street Address", name: "street", widget: "string"}
                  - {label: "City", name: "city", widget: "string"}
                  - {label: "Postal Code", name: "post-code", widget: "string"}
          - label: "Favorite Post"
            name: "favorite_post"
            widget: "relation"
            collection: "posts"
            search_fields: ['title']
            value_field: "{{slug}}"
            display_fields: ["{{title}}"]
          - label: "City"
            name: "airport-code"
            widget: "select"
            options:
              - { label: "Chicago", value: "ORD" }
              - { label: "Paris", value: "CDG" }
              - { label: "Tokyo", value: "HND" }
              - { label: "Singapore", value: "SG" }
          